# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'index.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QPlainTextEdit, QPushButton, QSizePolicy,
    QTabWidget, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1231, 967)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabs = QTabWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setGeometry(QRect(0, 0, 1241, 971))
        self.tabs.setTabShape(QTabWidget.Rounded)
        self.tabs.setDocumentMode(True)
        self.data_tab = QWidget()
        self.data_tab.setObjectName(u"data_tab")
        self.data_panel = QWidget(self.data_tab)
        self.data_panel.setObjectName(u"data_panel")
        self.data_panel.setGeometry(QRect(-10, 0, 1241, 81))
        self.data_panel.setAutoFillBackground(False)
        self.data_panel.setStyleSheet(u"background-color: rgb(19, 255, 176);")
        self.file_path = QLineEdit(self.data_panel)
        self.file_path.setObjectName(u"file_path")
        self.file_path.setEnabled(True)
        self.file_path.setGeometry(QRect(30, 30, 271, 31))
        self.file_path.setTabletTracking(False)
        self.file_path.setAutoFillBackground(False)
        self.file_path.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.file_path.setReadOnly(True)
        self.import_data = QPushButton(self.data_panel)
        self.import_data.setObjectName(u"import_data")
        self.import_data.setGeometry(QRect(320, 30, 101, 31))
        self.import_data.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.data_table = QTableWidget(self.data_tab)
        self.data_table.setObjectName(u"data_table")
        self.data_table.setGeometry(QRect(10, 100, 1211, 831))
        self.tabs.addTab(self.data_tab, "")
        self.stfn_tab = QWidget()
        self.stfn_tab.setObjectName(u"stfn_tab")
        self.stfn_settings = QWidget(self.stfn_tab)
        self.stfn_settings.setObjectName(u"stfn_settings")
        self.stfn_settings.setGeometry(QRect(0, 0, 391, 951))
        self.stfn_settings.setAutoFillBackground(False)
        self.stfn_settings.setStyleSheet(u"background-color: rgb(19, 255, 176);")
        self.criteria_types = QLineEdit(self.stfn_settings)
        self.criteria_types.setObjectName(u"criteria_types")
        self.criteria_types.setEnabled(True)
        self.criteria_types.setGeometry(QRect(10, 60, 371, 31))
        self.criteria_types.setTabletTracking(False)
        self.criteria_types.setAutoFillBackground(False)
        self.criteria_types.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.criteria_types.setReadOnly(False)
        self.bounds_gen_btn = QPushButton(self.stfn_settings)
        self.bounds_gen_btn.setObjectName(u"bounds_gen_btn")
        self.bounds_gen_btn.setGeometry(QRect(10, 310, 161, 51))
        self.bounds_gen_btn.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.criteria_label = QLabel(self.stfn_settings)
        self.criteria_label.setObjectName(u"criteria_label")
        self.criteria_label.setGeometry(QRect(10, 15, 141, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.criteria_label.setFont(font)
        self.criteria_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.bounds_label = QLabel(self.stfn_settings)
        self.bounds_label.setObjectName(u"bounds_label")
        self.bounds_label.setGeometry(QRect(10, 110, 141, 31))
        self.bounds_label.setFont(font)
        self.bounds_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.bounds_data = QPlainTextEdit(self.stfn_settings)
        self.bounds_data.setObjectName(u"bounds_data")
        self.bounds_data.setGeometry(QRect(10, 160, 361, 131))
        self.bounds_data.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.bounds_set_btn = QPushButton(self.stfn_settings)
        self.bounds_set_btn.setObjectName(u"bounds_set_btn")
        self.bounds_set_btn.setGeometry(QRect(210, 310, 161, 51))
        self.bounds_set_btn.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.expert_rank_label = QLabel(self.stfn_settings)
        self.expert_rank_label.setObjectName(u"expert_rank_label")
        self.expert_rank_label.setGeometry(QRect(10, 380, 181, 31))
        self.expert_rank_label.setFont(font)
        self.expert_rank_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.calc_stfn = QPushButton(self.stfn_settings)
        self.calc_stfn.setObjectName(u"calc_stfn")
        self.calc_stfn.setGeometry(QRect(10, 550, 361, 51))
        self.calc_stfn.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.pso_pop_size_label = QLabel(self.stfn_settings)
        self.pso_pop_size_label.setObjectName(u"pso_pop_size_label")
        self.pso_pop_size_label.setGeometry(QRect(10, 460, 201, 31))
        self.pso_pop_size_label.setFont(font)
        self.pso_pop_size_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.pso_pop_size = QLineEdit(self.stfn_settings)
        self.pso_pop_size.setObjectName(u"pso_pop_size")
        self.pso_pop_size.setEnabled(True)
        self.pso_pop_size.setGeometry(QRect(10, 500, 261, 31))
        self.pso_pop_size.setTabletTracking(False)
        self.pso_pop_size.setAutoFillBackground(False)
        self.pso_pop_size.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.pso_pop_size.setReadOnly(False)
        self.expert_rank = QLineEdit(self.stfn_settings)
        self.expert_rank.setObjectName(u"expert_rank")
        self.expert_rank.setEnabled(True)
        self.expert_rank.setGeometry(QRect(10, 410, 371, 31))
        self.expert_rank.setTabletTracking(False)
        self.expert_rank.setAutoFillBackground(False)
        self.expert_rank.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.expert_rank.setReadOnly(False)
        self.stfn_results = QPlainTextEdit(self.stfn_tab)
        self.stfn_results.setObjectName(u"stfn_results")
        self.stfn_results.setGeometry(QRect(400, 80, 811, 321))
        self.stfn_results.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.stfn_results_label = QLabel(self.stfn_tab)
        self.stfn_results_label.setObjectName(u"stfn_results_label")
        self.stfn_results_label.setGeometry(QRect(400, 30, 141, 31))
        self.stfn_results_label.setFont(font)
        self.stfn_results_label.setStyleSheet(u"")
        self.tabs.addTab(self.stfn_tab, "")
        self.mcda_tab = QWidget()
        self.mcda_tab.setObjectName(u"mcda_tab")
        self.stfn_settings_2 = QWidget(self.mcda_tab)
        self.stfn_settings_2.setObjectName(u"stfn_settings_2")
        self.stfn_settings_2.setGeometry(QRect(0, 0, 391, 951))
        self.stfn_settings_2.setAutoFillBackground(False)
        self.stfn_settings_2.setStyleSheet(u"background-color: rgb(19, 255, 176);")
        self.criteria_types_2 = QLineEdit(self.stfn_settings_2)
        self.criteria_types_2.setObjectName(u"criteria_types_2")
        self.criteria_types_2.setEnabled(True)
        self.criteria_types_2.setGeometry(QRect(10, 60, 371, 31))
        self.criteria_types_2.setTabletTracking(False)
        self.criteria_types_2.setAutoFillBackground(False)
        self.criteria_types_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.criteria_types_2.setReadOnly(True)
        self.bounds_gen_btn_2 = QPushButton(self.stfn_settings_2)
        self.bounds_gen_btn_2.setObjectName(u"bounds_gen_btn_2")
        self.bounds_gen_btn_2.setGeometry(QRect(10, 310, 161, 51))
        self.bounds_gen_btn_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.criteria_label_2 = QLabel(self.stfn_settings_2)
        self.criteria_label_2.setObjectName(u"criteria_label_2")
        self.criteria_label_2.setGeometry(QRect(10, 15, 141, 31))
        self.criteria_label_2.setFont(font)
        self.bounds_label_2 = QLabel(self.stfn_settings_2)
        self.bounds_label_2.setObjectName(u"bounds_label_2")
        self.bounds_label_2.setGeometry(QRect(10, 110, 141, 31))
        self.bounds_label_2.setFont(font)
        self.bounds_data_2 = QPlainTextEdit(self.stfn_settings_2)
        self.bounds_data_2.setObjectName(u"bounds_data_2")
        self.bounds_data_2.setGeometry(QRect(10, 160, 361, 131))
        self.bounds_data_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.bounds_set_btn_2 = QPushButton(self.stfn_settings_2)
        self.bounds_set_btn_2.setObjectName(u"bounds_set_btn_2")
        self.bounds_set_btn_2.setGeometry(QRect(210, 310, 161, 51))
        self.bounds_set_btn_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ranks_label_2 = QLabel(self.stfn_settings_2)
        self.ranks_label_2.setObjectName(u"ranks_label_2")
        self.ranks_label_2.setGeometry(QRect(10, 380, 141, 31))
        self.ranks_label_2.setFont(font)
        self.ranks_data_2 = QPlainTextEdit(self.stfn_settings_2)
        self.ranks_data_2.setObjectName(u"ranks_data_2")
        self.ranks_data_2.setGeometry(QRect(10, 420, 361, 131))
        self.ranks_data_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.calc_stfn_2 = QPushButton(self.stfn_settings_2)
        self.calc_stfn_2.setObjectName(u"calc_stfn_2")
        self.calc_stfn_2.setGeometry(QRect(10, 670, 361, 51))
        self.calc_stfn_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.training_data_label_2 = QLabel(self.stfn_settings_2)
        self.training_data_label_2.setObjectName(u"training_data_label_2")
        self.training_data_label_2.setGeometry(QRect(10, 570, 201, 31))
        self.training_data_label_2.setFont(font)
        self.training_data_2 = QLineEdit(self.stfn_settings_2)
        self.training_data_2.setObjectName(u"training_data_2")
        self.training_data_2.setEnabled(True)
        self.training_data_2.setGeometry(QRect(10, 610, 261, 31))
        self.training_data_2.setTabletTracking(False)
        self.training_data_2.setAutoFillBackground(False)
        self.training_data_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.training_data_2.setReadOnly(True)
        self.tabs.addTab(self.mcda_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.import_data.setText(QCoreApplication.translate("MainWindow", u"Import Data", None))
        self.tabs.setTabText(self.tabs.indexOf(self.data_tab), QCoreApplication.translate("MainWindow", u"Data", None))
        self.criteria_types.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1, 1, 1, -1, -1", None))
        self.bounds_gen_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Bounds", None))
        self.criteria_label.setText(QCoreApplication.translate("MainWindow", u"Types of criteria", None))
        self.bounds_label.setText(QCoreApplication.translate("MainWindow", u"Bounds for criteria", None))
        self.bounds_data.setPlaceholderText(QCoreApplication.translate("MainWindow", u"(44.6, 333.6), (10.1, 211.83), (8.14, 178.55), (5.68, 107.39), (1.27, 25.81)", None))
        self.bounds_set_btn.setText(QCoreApplication.translate("MainWindow", u"Set Bounds", None))
        self.expert_rank_label.setText(QCoreApplication.translate("MainWindow", u"Alternatives ranking", None))
        self.calc_stfn.setText(QCoreApplication.translate("MainWindow", u"Calculate STFN", None))
        self.pso_pop_size_label.setText(QCoreApplication.translate("MainWindow", u"Training data size", None))
        self.pso_pop_size.setText("")
        self.pso_pop_size.setPlaceholderText(QCoreApplication.translate("MainWindow", u"100", None))
        self.expert_rank.setPlaceholderText(QCoreApplication.translate("MainWindow", u"3, 1, 9, 10, 5, 7, 2, 6, 8, 4", None))
        self.stfn_results.setPlaceholderText("")
        self.stfn_results_label.setText(QCoreApplication.translate("MainWindow", u"Results", None))
        self.tabs.setTabText(self.tabs.indexOf(self.stfn_tab), QCoreApplication.translate("MainWindow", u"STFN", None))
        self.criteria_types_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1, 1, 1, -1, -1", None))
        self.bounds_gen_btn_2.setText(QCoreApplication.translate("MainWindow", u"Generate Bounds", None))
        self.criteria_label_2.setText(QCoreApplication.translate("MainWindow", u"Types of criteria", None))
        self.bounds_label_2.setText(QCoreApplication.translate("MainWindow", u"Bounds for criteria", None))
        self.bounds_data_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"(44.6, 333.6), (33, 20), (10.1, 211.83), (8.14, 178.55)", None))
        self.bounds_set_btn_2.setText(QCoreApplication.translate("MainWindow", u"Set Bounds", None))
        self.ranks_label_2.setText(QCoreApplication.translate("MainWindow", u"Alternatives ranking", None))
        self.ranks_data_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"3, 2, 4, 1", None))
        self.calc_stfn_2.setText(QCoreApplication.translate("MainWindow", u"Calculate STFN", None))
        self.training_data_label_2.setText(QCoreApplication.translate("MainWindow", u"Training data size", None))
        self.training_data_2.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.training_data_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabs.setTabText(self.tabs.indexOf(self.mcda_tab), QCoreApplication.translate("MainWindow", u"MCDA", None))
    # retranslateUi

