# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'index.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPlainTextEdit,
    QPushButton, QSizePolicy, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1231, 967)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabs = QTabWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setGeometry(QRect(0, 0, 1241, 971))
        self.tabs.setTabShape(QTabWidget.Rounded)
        self.tabs.setDocumentMode(True)
        self.data_tab = QWidget()
        self.data_tab.setObjectName(u"data_tab")
        self.data_panel = QWidget(self.data_tab)
        self.data_panel.setObjectName(u"data_panel")
        self.data_panel.setGeometry(QRect(-10, 0, 1241, 81))
        self.data_panel.setAutoFillBackground(False)
        self.data_panel.setStyleSheet(u"background-color: rgb(32, 164, 221);")
        self.file_path = QLineEdit(self.data_panel)
        self.file_path.setObjectName(u"file_path")
        self.file_path.setEnabled(True)
        self.file_path.setGeometry(QRect(30, 30, 271, 31))
        self.file_path.setTabletTracking(False)
        self.file_path.setAutoFillBackground(False)
        self.file_path.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.file_path.setReadOnly(True)
        self.import_data = QPushButton(self.data_panel)
        self.import_data.setObjectName(u"import_data")
        self.import_data.setGeometry(QRect(320, 30, 101, 31))
        self.import_data.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.data_table = QTableWidget(self.data_tab)
        self.data_table.setObjectName(u"data_table")
        self.data_table.setGeometry(QRect(10, 100, 1211, 831))
        self.data_table.setAutoFillBackground(False)
        self.tabs.addTab(self.data_tab, "")
        self.stfn_tab = QWidget()
        self.stfn_tab.setObjectName(u"stfn_tab")
        self.stfn_settings = QWidget(self.stfn_tab)
        self.stfn_settings.setObjectName(u"stfn_settings")
        self.stfn_settings.setGeometry(QRect(0, 0, 391, 951))
        self.stfn_settings.setAutoFillBackground(False)
        self.stfn_settings.setStyleSheet(u"background-color: rgb(32, 164, 221);")
        self.bounds_gen_btn = QPushButton(self.stfn_settings)
        self.bounds_gen_btn.setObjectName(u"bounds_gen_btn")
        self.bounds_gen_btn.setGeometry(QRect(110, 220, 161, 51))
        self.bounds_gen_btn.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.bounds_label = QLabel(self.stfn_settings)
        self.bounds_label.setObjectName(u"bounds_label")
        self.bounds_label.setGeometry(QRect(10, 20, 141, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.bounds_label.setFont(font)
        self.bounds_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.bounds_data = QPlainTextEdit(self.stfn_settings)
        self.bounds_data.setObjectName(u"bounds_data")
        self.bounds_data.setGeometry(QRect(10, 70, 371, 131))
        self.bounds_data.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.expert_rank_label = QLabel(self.stfn_settings)
        self.expert_rank_label.setObjectName(u"expert_rank_label")
        self.expert_rank_label.setGeometry(QRect(10, 290, 181, 31))
        self.expert_rank_label.setFont(font)
        self.expert_rank_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.calc_stfn = QPushButton(self.stfn_settings)
        self.calc_stfn.setObjectName(u"calc_stfn")
        self.calc_stfn.setGeometry(QRect(10, 460, 371, 51))
        self.calc_stfn.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.pso_pop_size_label = QLabel(self.stfn_settings)
        self.pso_pop_size_label.setObjectName(u"pso_pop_size_label")
        self.pso_pop_size_label.setGeometry(QRect(10, 370, 201, 31))
        self.pso_pop_size_label.setFont(font)
        self.pso_pop_size_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.pso_pop_size = QLineEdit(self.stfn_settings)
        self.pso_pop_size.setObjectName(u"pso_pop_size")
        self.pso_pop_size.setEnabled(True)
        self.pso_pop_size.setGeometry(QRect(10, 410, 371, 31))
        self.pso_pop_size.setTabletTracking(False)
        self.pso_pop_size.setAutoFillBackground(False)
        self.pso_pop_size.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.pso_pop_size.setReadOnly(False)
        self.expert_rank = QLineEdit(self.stfn_settings)
        self.expert_rank.setObjectName(u"expert_rank")
        self.expert_rank.setEnabled(True)
        self.expert_rank.setGeometry(QRect(10, 320, 371, 31))
        self.expert_rank.setTabletTracking(False)
        self.expert_rank.setAutoFillBackground(False)
        self.expert_rank.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.expert_rank.setReadOnly(False)
        self.stfn_results = QPlainTextEdit(self.stfn_tab)
        self.stfn_results.setObjectName(u"stfn_results")
        self.stfn_results.setGeometry(QRect(400, 80, 811, 181))
        self.stfn_results.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.stfn_results_label = QLabel(self.stfn_tab)
        self.stfn_results_label.setObjectName(u"stfn_results_label")
        self.stfn_results_label.setGeometry(QRect(400, 30, 141, 31))
        self.stfn_results_label.setFont(font)
        self.stfn_results_label.setStyleSheet(u"")
        self.stfn_plot_label = QLabel(self.stfn_tab)
        self.stfn_plot_label.setObjectName(u"stfn_plot_label")
        self.stfn_plot_label.setGeometry(QRect(400, 280, 141, 31))
        self.stfn_plot_label.setFont(font)
        self.stfn_plot_label.setStyleSheet(u"")
        self.stfn_plot = QGraphicsView(self.stfn_tab)
        self.stfn_plot.setObjectName(u"stfn_plot")
        self.stfn_plot.setGeometry(QRect(400, 330, 811, 601))
        self.prev_plot_btn_stfn = QPushButton(self.stfn_tab)
        self.prev_plot_btn_stfn.setObjectName(u"prev_plot_btn_stfn")
        self.prev_plot_btn_stfn.setGeometry(QRect(480, 280, 91, 31))
        self.next_plot_btn_stfn = QPushButton(self.stfn_tab)
        self.next_plot_btn_stfn.setObjectName(u"next_plot_btn_stfn")
        self.next_plot_btn_stfn.setGeometry(QRect(590, 280, 91, 31))
        self.tabs.addTab(self.stfn_tab, "")
        self.mcda_tab = QWidget()
        self.mcda_tab.setObjectName(u"mcda_tab")
        self.mcda_settings = QWidget(self.mcda_tab)
        self.mcda_settings.setObjectName(u"mcda_settings")
        self.mcda_settings.setGeometry(QRect(0, 0, 391, 951))
        self.mcda_settings.setAutoFillBackground(False)
        self.mcda_settings.setStyleSheet(u"background-color: rgb(32, 164, 221);")
        self.mcda_method_label = QLabel(self.mcda_settings)
        self.mcda_method_label.setObjectName(u"mcda_method_label")
        self.mcda_method_label.setGeometry(QRect(10, 15, 141, 31))
        self.mcda_method_label.setFont(font)
        self.mcda_method_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.calc_mcda = QPushButton(self.mcda_settings)
        self.calc_mcda.setObjectName(u"calc_mcda")
        self.calc_mcda.setGeometry(QRect(10, 340, 361, 51))
        self.calc_mcda.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.mcda_method = QComboBox(self.mcda_settings)
        self.mcda_method.addItem("")
        self.mcda_method.addItem("")
        self.mcda_method.addItem("")
        self.mcda_method.setObjectName(u"mcda_method")
        self.mcda_method.setGeometry(QRect(10, 60, 371, 31))
        self.mcda_method.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.criteria_types = QLineEdit(self.mcda_settings)
        self.criteria_types.setObjectName(u"criteria_types")
        self.criteria_types.setEnabled(True)
        self.criteria_types.setGeometry(QRect(10, 170, 371, 31))
        self.criteria_types.setTabletTracking(False)
        self.criteria_types.setAutoFillBackground(False)
        self.criteria_types.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.criteria_types.setReadOnly(False)
        self.criteria_label = QLabel(self.mcda_settings)
        self.criteria_label.setObjectName(u"criteria_label")
        self.criteria_label.setGeometry(QRect(10, 125, 141, 31))
        self.criteria_label.setFont(font)
        self.criteria_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.weights_label = QLabel(self.mcda_settings)
        self.weights_label.setObjectName(u"weights_label")
        self.weights_label.setGeometry(QRect(10, 225, 171, 31))
        self.weights_label.setFont(font)
        self.weights_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.criteria_weights = QLineEdit(self.mcda_settings)
        self.criteria_weights.setObjectName(u"criteria_weights")
        self.criteria_weights.setEnabled(True)
        self.criteria_weights.setGeometry(QRect(10, 270, 371, 31))
        self.criteria_weights.setTabletTracking(False)
        self.criteria_weights.setAutoFillBackground(False)
        self.criteria_weights.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.criteria_weights.setReadOnly(False)
        self.mcda_ranking_new_label = QLabel(self.mcda_tab)
        self.mcda_ranking_new_label.setObjectName(u"mcda_ranking_new_label")
        self.mcda_ranking_new_label.setGeometry(QRect(400, 20, 141, 31))
        self.mcda_ranking_new_label.setFont(font)
        self.mcda_ranking_new_label.setStyleSheet(u"")
        self.ranking_new = QPlainTextEdit(self.mcda_tab)
        self.ranking_new.setObjectName(u"ranking_new")
        self.ranking_new.setGeometry(QRect(400, 70, 811, 91))
        self.ranking_new.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.mcda_ranking_old_label = QLabel(self.mcda_tab)
        self.mcda_ranking_old_label.setObjectName(u"mcda_ranking_old_label")
        self.mcda_ranking_old_label.setGeometry(QRect(400, 190, 141, 31))
        self.mcda_ranking_old_label.setFont(font)
        self.mcda_ranking_old_label.setStyleSheet(u"")
        self.ranking_old = QPlainTextEdit(self.mcda_tab)
        self.ranking_old.setObjectName(u"ranking_old")
        self.ranking_old.setGeometry(QRect(400, 240, 811, 91))
        self.ranking_old.setStyleSheet(u"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.mcda_plot = QGraphicsView(self.mcda_tab)
        self.mcda_plot.setObjectName(u"mcda_plot")
        self.mcda_plot.setGeometry(QRect(400, 390, 811, 541))
        self.graph_label = QLabel(self.mcda_tab)
        self.graph_label.setObjectName(u"graph_label")
        self.graph_label.setGeometry(QRect(400, 350, 141, 31))
        self.graph_label.setFont(font)
        self.graph_label.setStyleSheet(u"")
        self.tabs.addTab(self.mcda_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.import_data.setText(QCoreApplication.translate("MainWindow", u"Import Data", None))
        self.tabs.setTabText(self.tabs.indexOf(self.data_tab), QCoreApplication.translate("MainWindow", u"Data", None))
        self.bounds_gen_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Bounds", None))
        self.bounds_label.setText(QCoreApplication.translate("MainWindow", u"Bounds for criteria", None))
        self.bounds_data.setPlaceholderText(QCoreApplication.translate("MainWindow", u"(44.6, 333.6), (10.1, 211.83), (8.14, 178.55), (5.68, 107.39), (1.27, 25.81)", None))
        self.expert_rank_label.setText(QCoreApplication.translate("MainWindow", u"Alternatives ranking", None))
        self.calc_stfn.setText(QCoreApplication.translate("MainWindow", u"Calculate STFN", None))
        self.pso_pop_size_label.setText(QCoreApplication.translate("MainWindow", u"Population size", None))
        self.pso_pop_size.setText("")
        self.pso_pop_size.setPlaceholderText(QCoreApplication.translate("MainWindow", u"100 (recommended)", None))
        self.expert_rank.setPlaceholderText(QCoreApplication.translate("MainWindow", u"3, 1, 9, 10, 5, 7, 2, 6, 8, 4", None))
        self.stfn_results.setPlaceholderText("")
        self.stfn_results_label.setText(QCoreApplication.translate("MainWindow", u"Results", None))
        self.stfn_plot_label.setText(QCoreApplication.translate("MainWindow", u"Graphs", None))
        self.prev_plot_btn_stfn.setText(QCoreApplication.translate("MainWindow", u"prev plot", None))
        self.next_plot_btn_stfn.setText(QCoreApplication.translate("MainWindow", u"next plot", None))
        self.tabs.setTabText(self.tabs.indexOf(self.stfn_tab), QCoreApplication.translate("MainWindow", u"STFN", None))
        self.mcda_method_label.setText(QCoreApplication.translate("MainWindow", u"MCDA method", None))
        self.calc_mcda.setText(QCoreApplication.translate("MainWindow", u"calculate ranking", None))
        self.mcda_method.setItemText(0, QCoreApplication.translate("MainWindow", u"TOPSIS", None))
        self.mcda_method.setItemText(1, QCoreApplication.translate("MainWindow", u"WASPAS", None))
        self.mcda_method.setItemText(2, QCoreApplication.translate("MainWindow", u"VIKOR", None))

        self.criteria_types.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1, 1, 1, -1, -1", None))
        self.criteria_label.setText(QCoreApplication.translate("MainWindow", u"Types of criteria", None))
        self.weights_label.setText(QCoreApplication.translate("MainWindow", u"Criteria weights", None))
        self.criteria_weights.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0.14192737, 0.22833073, 0.22020835, 0.21593906, 0.19359448", None))
        self.mcda_ranking_new_label.setText(QCoreApplication.translate("MainWindow", u"New Ranking", None))
        self.ranking_new.setPlaceholderText("")
        self.mcda_ranking_old_label.setText(QCoreApplication.translate("MainWindow", u"Old Ranking", None))
        self.ranking_old.setPlaceholderText("")
        self.graph_label.setText(QCoreApplication.translate("MainWindow", u"Graphs", None))
        self.tabs.setTabText(self.tabs.indexOf(self.mcda_tab), QCoreApplication.translate("MainWindow", u"MCDA", None))
    # retranslateUi

